---
- block:
    - name: Download and install the Public Signing Key
      apt_key:
        url: '{{ elastic_gpg_key }}'
        state: present

    - name: Install dependencies for Debian
      apt:
        name: apt-transport-https
        state: present
      register: debian_dependency
      until: debian_dependency is succeeded

    - name: Add Beats repository
      apt_repository:
        repo: '{{ es_apt_url }}'
        state: present
        update_cache: true

    - name: Install metricbeat
      apt:
        name: metricbeat
        state: present

    - name: Run & enable metricbeat service
      systemd:
        name: '{{ metricbeat_service_name }}'
        enabled: yes
        state: started
  become: true