---
- name: Installing filebeat on current OS
  include_tasks: '{{ distrib_tasks }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - not-supported.yml
  loop_control:
    loop_var: distrib_tasks

- name: Place config file metricbeat
  template:
    src: 'metricbeat.yml.j2'
    dest: '{{ path.config }}/metricbeat.yml'
    owner: root
    group: root
    mode: 0644
  notify: Restart filebeat
  when: metricbeat_config is defined
  become: true

- name: Enable modules for metricbeat
  command: 'metricbeat modules enable {{ item }}'
  with_items: '{{ metricbeat_modules }}'