---
- block:
    - name: Download and install the Public Signing Key
      rpm_key:
        url: '{{ elastic_gpg_key_redhat }}'
        state: present

    - name: Add Beats repository
      yum_repository:
        name: '{{ metricbeat_service_name }}'
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes
        gpgkey: '{{ elastic_gpg_key }}'
        enabled: yes
        state: present

    - name: Install metricbeat
      yum:
        name: metricbeat
        state: present
        update_cache: true

    - name: Run & enable metricbeat service
      systemd:
        name: '{{ metricbeat_service_name }}'
        enabled: yes
        state: started
  become: true